[project]
name = "subsplease"
version = "0.2.0"
description = "A package for fetching and parsing episodes from SubsPlease API."
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["httpx>=0.27.2"]
